name: insure_partner
description: Zero-Touch Parametric Income Protection for Q-Commerce Delivery Partners.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.12.2
  provider: ^6.1.5
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
